site_name: CES Big Data
site_url: https://jorsodom.github.io/bigdata-sb/


nav:
  - Inicio: index.md
  #- Big Data con Hadoop: 
  #  - 0. Consulta previa Big Data: hadoop/PreviaBigData.md
  #  - 0.1 Big Data Introducción : hadoop/IntroBigData.md
  #  - 1. Introducción: hadoop/HadoopIntro.md
  #  - 2. HDFS: hadoop/HadoopHDFS.md
  #  - 3. MapReduce: hadoop/HadoopMapReduce.md
     

  - Presentación: introduccionBI/presentacions.md
  - UD1. Introducción: 
    - Introducción BI: introduccionBI/BIIntroduccion.md
    - Análisis de datos: introduccionBI/analitica.md
    - Introducción ETL: introduccionBI/ETLintroduccion.md
    - Tipos datos: introduccionBI/tiposdedatos.md
  - UD2. Entornos y modelado: 
      - Tipos de entornos y arquitecturas de datos: multidimensional/entornos.md
      - Modelo multidimensional (OLAP): multidimensional/multidimensional.md
  - UD3. Bases de datos NoSQL con MongoDB: https://alapvi.github.io/sbd/
  - UD4. Ingesta de datos con NiFi: 
      - Introducción: nifi/nifiIntroduccion.md
      - Ejemplos: nifi/nifiEjemplos.md
      - Práctica 1: nifi/nifiPractica1.md
      - Práctica 2: nifi/nifiPractica2.md
      - Práctica 3: nifi/nifiPractica3.md
  #  - Práctica 4: nifi/nifiPractica4.md
  #  - Práctica 5: nifi/nifiPractica5.md
  #  - Práctica 6: nifi/nifiPractica6.md
  #  - Práctica 7: nifi/nifiPractica7.md
  #  - Práctica 8: nifi/nifiPractica8.md
  #  - Práctica 10: nifi/nifiPractica10.md
  #  - Caso de uso con Hadoop: nifi/nifiCasoUsoHadoop.md
  #  - Caso de uso Meteo: nifi/nifiCasoUsoMeteo.md
  #  - Caso uso API: nifi/nifiCasoUsoAPI.md
  #  - Caso de uso con PostgreSQL: nifi/nifiCasoUsoPostgreSQL.md
  #- ETL con ODI: 
  #  - Introducción: odi/odiIntroduccion.md
  #  - Demo: odi/odiDemo.md
  #  - Caso de uso: odi/odiCasoDeUso.md
  #- Microsoft Azure: 
  #   - Introducción: azure/AzureIntroduccion.md
  #   - Práctica 1: azure/AzurePractica1.md
theme:
  name: material
  language: es
  features:
    - content.code.copy

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jorsodom/
      name: Jorge Soro
  consent:
    title: Consentimiento Cookie
    description: >- 
      Utilizamos cookies para reconocer sus visitas repetidas y preferencias, así como
      para medir la eficacia de nuestra documentación y si los usuarios
      encuentran lo que buscan. Con su consentimiento, nos ayuda a
      mejorar nuestra documentación.

copyright: Copyright &copy; 2022- 2026 